export const issueExplanations: Record<string, string> = {
    KnownPhishingDomain: "This domain is listed in known phishing databases like PhishTank or OpenPhish, indicating a high risk of fraud or credential theft.",
    NumbersInDomain: "Attackers often use numbers to impersonate popular brands (e.g., 'g00gle' instead of 'google'), which is a common typosquatting technique.",
    ExcessiveSubdomains: "A large number of subdomains can be used to obfuscate a URL's real destination and make it harder for users to detect malicious intent.",
    SpecialCharacters: "Unusual or encoded characters in URLs may be used to bypass filters or trick users visually, often seen in phishing campaigns.",
    DomainTooNew: "Phishing sites are typically short-lived. Recently registered domains are more likely to be used in malicious campaigns.",
    DomainAgeUnknown: "The WHOIS creation date for this domain couldn't be retrieved, which could be due to registrar restrictions or hidden ownership. This uncertainty can indicate risk.",
    DomainAgeCheckFailed: "An error occurred while trying to verify the domain's registration age. Domains with unknown age should be treated cautiously.",
    DDNSDetected: "Dynamic DNS services (e.g., no-ip.org, duckdns.org) are often used by attackers to host phishing pages that can change IPs frequently.",
    NoSSLCertificate: "The domain does not use HTTPS, meaning data sent to the site could be intercepted. Legitimate services almost always use HTTPS.",
    ExpiredSSLCertificate: "An expired certificate indicates poor site maintenance or a potential phishing site mimicking a real one.",
    WeakSSLIssuer: "SSL certificates from weak or free issuers (e.g., self-signed, Let's Encrypt in suspicious contexts) may be used to feign legitimacy.",
    SSLConnectionError: "The server could not establish a secure SSL connection, indicating a misconfigured or suspicious setup.",
    SSLTimeout: "The server took too long to respond to a secure connection request, which may suggest an unstable or hidden endpoint.",
    TooManyRedirects: "Multiple redirects are often used to hide the final destination of a phishing page, making it harder to analyze or block.",
    InsecureRedirect: "Redirecting from HTTPS to HTTP weakens security and is considered a bad practice, often used to trick users.",
    CrossDomainRedirect: "Redirecting between unrelated domains can indicate obfuscation or malicious redirection behavior.",
    RedirectCheckFailed: "An error occurred while trying to follow redirects. This may indicate a misconfigured or inaccessible destination.",
    SimilarToKnownDomain: "This domain is visually or typographically similar to a trusted one (e.g., 'g00gle.com'), which is a hallmark of typosquatting attacks.",
    LoginFormDetected: "The page contains a login form, which could be used to capture user credentials if the site is malicious.",
    SensitiveFieldDetected: "The page requests personal or financial data (e.g., SSN, credit card), which is highly suspicious outside of trusted services.",
    FormDetected: "The site includes a form, which could potentially be used for data collection or phishing attempts.",
    FormAnalysisFailed: "Failed to analyze the site's HTML content, possibly due to DNS errors or blocking. Lack of visibility adds uncertainty."
};
